sudo: required
services:
  - docker
install:
  - docker version
  - docker-compose version
  - rm docker-compose.override.yml
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
script:
  - docker-compose run --rm dbmate make wait
  - docker-compose run --rm dbmate make test
  - docker-compose run --rm dbmate make lint
  - docker build -t dbmate .
  - docker run --rm dbmate --help
