blank_issues_enabled: true
contact_links:
  - name: "ğŸ™‹â€â™€ï¸ Question"
    url: https://github.com/amacneil/dbmate/discussions
    about: Search discussions or ask our community for help
  - name: "ğŸš€ Feature request"
    url: https://github.com/amacneil/dbmate/discussions
    about: Search existing feature requests or share a new idea
