name: CI

on:
  push:
    branches: [main]
    tags: "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setu up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [worker.oci]
              platforms = [ "linux/amd64", "linux/arm64" ]
            [worker.containerd]
              platforms = [ "linux/amd64", "linux/arm64" ]

      - name: Environment
        run: |
          set -x
          docker version
          docker buildx version
          docker-compose version

      - name: Cache
        uses: actions/cache@v2
        with:
          key: cache
          path: .cache

      - name: Build docker image
        run: |
          set -x
          docker buildx bake --set dbmate.platform="linux/arm64,linux/amd64"
          docker-compose run --rm --no-deps dbmate --version

      - name: Build binaries
        run: |
          set -x
          docker-compose run --rm --no-deps dev make build-all
          dist/dbmate-linux-amd64 --version

      - name: Lint
        run: docker-compose run --rm --no-deps dev make lint

      - name: Start test dependencies
        run: |
          set -x
          docker-compose pull --quiet
          docker-compose up --detach

      - name: Run tests
        run: |
          set -x
          docker-compose run --rm dev make wait
          docker-compose run --rm dev make test

      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        env:
          SRC_IMAGE: dbmate_release
          DOCKERHUB_IMAGE: ${{ github.repository }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GHCR_IMAGE: ghcr.io/${{ github.repository }}
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/workflows/publish-docker.sh

      - name: Publish release binaries
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
