name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:
  docker:
    name: Docker Test (linux/amd64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker environment
        run: |
          set -x
          docker version
          docker buildx version
          docker compose version

      - name: Build Docker image
        run: |
          set -x
          docker compose build
          docker compose run --rm --no-deps dbmate --version

      - name: Run make build
        run: docker compose run --rm --no-deps dev make build ls

      - name: Run make lint
        run: docker compose run --rm --no-deps dev make lint

      - name: Start test dependencies
        run: |
          set -x
          docker compose pull --ignore-buildable --quiet
          docker compose up --detach
          docker compose run --rm dev make wait

      - name: Run make test
        run: docker compose run --rm dev make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker image tags
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Publish Docker image
        uses: docker/build-push-action@v6
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          target: release
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Automatically approve dependabot PRs
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          event: APPROVE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
